### PR TITLE
Fixed or Addressed Issues #3, #4 and #5

### PR DESCRIPTION
**Pull request by LevonBecker**
Hey I forked and fixed up the stuff we were discussing in the issues I created. It looks like I deleted and recreated two files, but that's just because I fixed the files to be LF instead of CRLF (dang winderz editors). You can set you git client to convert all files to LF when uploading to repo (Highly recommended if working from a Windows system).

Change Details:
* Added .gitignore so didn't upload any of my idea (jetbrains) tracking files
* Updated Readme.md heavily with clarifications
* Converted **AutoSitemap_body.php** and **sitemap.xsl** from CRLF to LF file format.

ToDo:
[ ] Code Review by @dolfinus 
* Double check this correction bug correction I did (It kinda got hidden in the diff because of the CRLF to LF conversion making it look like the whole file was diff when it's not... )
So, I'll write out the Diff here:

### Before:
```php
global $wgAutoSitemap, $wgServer, $wgServer, $wgCanonicalServer, $wgScriptPath;
if (!isset($wgAutoSitemap["filename"]          )) $wgAutoSitemap["filename"]           = "sitemap.xml";
if (!isset($wgAutoSitemap["server"]            )) $wgAutoSitemap["server"]             = isset($wgCanonicalServer) ? $wgCanonicalServer : $wgServer;
if (!isset($wgAutoSitemap["notify"]            )) $wgAutoSitemap["notify"]             = [
                                                                                            'https://www.google.com/webmasters/sitemaps/ping?sitemap='.$wgScriptPath."/".$wgAutoSitemap["filename"],
                                                                                            'https://www.bing.com/webmaster/ping.aspx?sitemap='.$wgScriptPath."/".$wgAutoSitemap["filename"],
                                                                                         ];
```

### After
```php
global $wgAutoSitemap, $wgServer, $wgServer, $wgCanonicalServer, $wgScriptPath;
if (!isset($wgAutoSitemap["filename"]          )) $wgAutoSitemap["filename"]           = "sitemap.xml";
if (!isset($wgAutoSitemap["server"]            )) $wgAutoSitemap["server"]             = isset($wgCanonicalServer) ? $wgCanonicalServer : $wgServer;
if (!isset($wgAutoSitemap["notify"]            )) $wgAutoSitemap["notify"]             = [
                                                                                            'https://www.google.com/webmasters/sitemaps/ping?sitemap='.$wgAutoSitemap["server"]."/".$wgAutoSitemap["filename"],
                                                                                            'https://www.bing.com/webmaster/ping.aspx?sitemap='.$wgAutoSitemap["server"]."/".$wgAutoSitemap["filename"],
                                                                                         ];
```

Notice **.$wgScriptPath.** to **.$wgAutoSitemap["server"].** in the default notification URLs. Basically meaning if you set the $wgAutoSitemap["server"] in LocalSettings.php it wouldn't do anything with these URLs. Although, obviously if you added the notify map to your LocalSettings.php it would skip this an make it hard to notice the bug.

Hope this helps!

### CODE REVIEW

**Comment by dolfinus** [comment]
Ew, lots of changes you made explains not the extension work, but some Mediawiki circumstances and such base things as debugging, user rights and server settings.

**Comment by LevonBecker** [comment]
Ok well you probably want to grab the bug fix and add it to the **AutoSitemap_body.php** and fix the incorrect CRLF file formats.

**Comment by dolfinus** [comment]
Thanks for founding a bug with notification urls and you Readme changes!
I`ve added fixes to code tree.

As for line endings, they will be the same.

**Comment by LevonBecker** [comment]
Sure thing

**Pull request closed without merging**
