### PR TITLE
Use DB_REPLICA and update version

### LINKED ISSUE #13: Not compatible with MW 1.34
When editing an article, the following error message appears:
`MWException from line 164 of <path>/includes/Hooks.php: Invalid callback AutoSitemap::writeSitemap in hooks for RevisionInsertComplete`

### PR DESCRIPTION
**Pull request by Ammarpad**
* Update to support MediaWiki 1.34
* Fix typo: Rewrited -> Rewrote

### CODE REVIEW

**Comment by dolfinus** [comment]
Hi.

Please also change extension version in extension.json and AutoSitemap_body.php files.

**Comment by Ammarpad** [comment]
> Hi.
> 
> Please also change extension version in extension.json and AutoSitemap_body.php files to 1.4.

Done. Thanks.

**Comment by dolfinus** [comment]
And here too if you don't mind: https://github.com/dolfinus/AutoSitemap/blob/master/AutoSitemap_body.php#L46

**Comment by Ammarpad** [comment]
I can do that. But I have no idea what the description should say.

**Comment by dolfinus** [comment]
"MW 1.34 support"

**Comment by Ammarpad** [comment]
Done. Also fixed typo in [AutoSitemap_body.php#L41](https://github.com/dolfinus/AutoSitemap/blob/e9118e4ef7b3a600251d688002c51883f7cceb63/AutoSitemap_body.php#L41)

**Pull request merged**
