### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by TaylanUB**
Just a bit of code cleanup, since we don't need the `$pos` and `$count` variables/arguments anymore.

### CODE REVIEW

**Comment by TaylanUB** [comment]
It shows 6 commits but it's really just the last one that's relevant. The other five should disappear when the other PRs are accepted.

(From a quick Google search, it seems that GitHub doesn't support a way to say that a PR's commits are based on those in another PR. Please tell me if you know a better way to create these PRs.)

**Comment by TaylanUB** [comment]
Actually, I just added a second commit to this PR: Delete the temporary file in case of an error.

**Comment by TaylanUB** [comment]
Rebased on the newest state of the `rate-limiting` branch.

**Comment by dolfinus** [comment]
Could you please rebase it one more time?

**Comment by TaylanUB** [comment]
Done.

**Comment by dolfinus** [comment]
Thank you!

**Pull request merged**
